name: Items External Integration

on:
  workflow_dispatch:

jobs:
  call-endpoints:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Call Items GET Endpoint
      run: |
        curl -X GET "${{ secrets.API_BASE_URL }}/pull-items" -H "x-api-key: ${{ secrets.EXTERNAL_INTEGRATOR_AUTH_TOKEN }}"
    