name: Cron Job - Projects External Integrator

on:
  schedule:
    - cron: '30 5 * * 1-6' # 12:30 AM EST
  workflow_dispatch:

jobs:
  call-endpoints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Call Items GET Endpoint
      run: |
        curl -X GET "${{ secrets.API_BASE_URL }}/pull-projects" -H "x-api-key: ${{ secrets.EXTERNAL_INTEGRATOR_AUTH_TOKEN }}"
